# Generated by Django 3.1.4 on 2020-12-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='kategoria',
            field=models.CharField(choices=[('Baza', 'Baza'), ('Toping', 'Toping')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='status',
            field=models.CharField(choices=[('Oczekiwanie', 'Oczekiwanie'), ('Wypiekanie', 'Wypiekanie'), ('Stygnięcie', 'Stygnięcie')], max_length=80, null=True),
        ),
    ]
